server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        - id: First-microservice
          uri: lb://First-microservice
          predicates:
            - Path=/first/**
        - id: Second-microservice
          uri: lb://Second-microservice
          predicates:
            - Path=/second/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost